overrides: "git://github.com/pyexcel/pyexcel-mobans!/mobanfile.yaml"
configuration:
  configuration: pyexcel-pdfr.yml
targets:
  - README.rst: custom_readme.rst.jj2
  - setup.py: custom_setup.py.jj2
  - MANIFEST.in: MANIFEST.in.jj2
  - "tests/requirements.txt": "tests/custom_req.txt.jj2"
  - "docs/source/conf.py": "docs/source/conf.py.jj2"
  - "pyexcel_pdfr/_version.py": version.py.jj2
  - .travis.yml: custom_travis.yml.jj2